//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.17
//

package com.mysampleapp.demo.bots;

import java.io.Serializable;




public class Bot implements Serializable {

    private String botName;
    private String botAlias;
    private String description;
    private String region;
    private String[] helpCommands;
    private String botTitle;

    public String getBotName(){
        return this.botName;
    }

    public String getBotAlias(){
        return this.botAlias;
    }

    public String getDescription(){
        return this.description;
    }

    public String getRegion(){
        return this.region;
    }

    public String[] getHelpCommands() {
        return helpCommands;
    }

    public String getBotTitle() {
        return this.botTitle;
    }

    public Bot(final String botName,
               final String botAlias,
               final String botTitle,
               final String description,
               final String region,
               final String[] helpCommands){
        this.botName = botName;
        this.botAlias = botAlias;
        this.description  =description;
        this.region = region;
        this.helpCommands = helpCommands;
        this.botTitle = botTitle;
    }
}
